export const FACILITY_MANAGEMENT_ENTITIES = [
  {
    name: 'Tesis Yönetimi',
    slug: 'tesis-yonetimi',
    pillarUrl: '/hizmetler/tesis-yonetimi',
    wikidata: 'https://www.wikidata.org/wiki/Q1391515',
    isoStandard: 'ISO 41001:2018',
    variations: [
      'tesis yönetimi',
      'entegre tesis yönetimi',
      'profesyonel tesis yönetimi',
      'istanbul tesis yönetimi',
      'tesis işletme yönetimi',
      'tesis yönetim şirketi',
      'tesis yönetim şirketleri',
      'tesis yönetim firmaları',
      'bina ve tesis yönetimi',
      'site ve tesis yönetimi',
      'iso 41001 tesis yönetimi',
      'facility management',
      'entegre gayrimenkul yönetimi',
    ],
  },
  {
    name: 'Tesis ve Mülk Hizmetleri',
    slug: 'tesis-ve-mulk-hizmetleri',
    pillarUrl: '/hizmetler/tesis-yonetimi',
    wikidata: 'https://www.wikidata.org/wiki/Q1758229',
    isoStandard: 'ISO 41001 & KMK 634',
    variations: [
      'tesis ve mülk hizmetleri',
      'tesis ve mülk yönetimi',
      'mülk hizmetleri',
      'mülk yönetimi',
      'gayrimenkul tesis işletmeciliği',
      'mülk varlık yönetimi',
      'istanbul mülk yönetimi',
      'profesyonel mülk yönetimi',
    ],
  },
  {
    name: 'Rezidans & Lüks Site Yönetimi',
    slug: 'rezidans-site-yonetimi',
    pillarUrl: '/hizmetler/tesis-yonetimi/rezidans-site-yonetimi',
    wikidata: 'https://www.wikidata.org/wiki/Q108846399',
    isoStandard: 'ISO 41001:2018',
    variations: [
      'rezidans yönetimi',
      'rezidans tesis yönetimi',
      'lüks site yönetimi',
      'rezidans concierge',
      'kule yönetimi',
    ],
  },
  {
    name: 'Plaza & Ofis Binası Tesis Yönetimi',
    slug: 'plaza-yonetimi',
    pillarUrl: '/hizmetler/tesis-yonetimi/plaza-yonetimi',
    wikidata: 'https://www.wikidata.org/wiki/Q102163',
    isoStandard: 'ISO 41001:2018',
    variations: [
      'plaza yönetimi',
      'iş merkezi yönetimi',
      'ofis binası yönetimi',
      'plaza tesis işletmesi',
    ],
  },
  {
    name: 'Toplu Konut & TOKİ Yönetimi',
    slug: 'toplu-konut-yonetimi',
    pillarUrl: '/hizmetler/tesis-yonetimi/toplu-konut-yonetimi',
    wikidata: 'https://www.wikidata.org/wiki/Q1391515',
    isoStandard: 'ISO 41001:2018',
    variations: [
      'toplu konut yönetimi',
      'toki site yönetimi',
      'çok bloklu site yönetimi',
      'kitlesel konut yönetimi',
    ],
  },
  {
    name: 'Sanayi Tesisi & Fabrika Yönetimi',
    slug: 'sanayi-tesisi-yonetimi',
    pillarUrl: '/hizmetler/tesis-yonetimi/sanayi-tesisi-yonetimi',
    wikidata: 'https://www.wikidata.org/wiki/Q83405',
    isoStandard: 'ISO 45001 & ISO 41001',
    variations: [
      'sanayi tesisi yönetimi',
      'fabrika yönetimi',
      'lojistik merkezi yönetimi',
      'organize sanayi tesis bakımı',
    ],
  },
  {
    name: 'Site ve Toplu Yapı Yönetimi',
    slug: 'site-yonetimi',
    pillarUrl: '/hizmetler/tesis-yonetimi',
    wikidata: 'https://www.wikidata.org/wiki/Q1758229',
    variations: [
      'site yönetimi',
      'profesyonel site yönetimi',
      'apartman yönetimi',
      'toplu yapı yönetimi',
      'site yönetim şirketleri',
      'site yönetim firması',
      'bina yönetimi',
    ],
  },
  {
    name: 'Kat Mülkiyeti Kanunu (KMK 634)',
    slug: 'kmk-634',
    pillarUrl: '/hizmetler/hukuk-ve-icra-danismanligi',
    wikidata: 'https://www.wikidata.org/wiki/Q161851',
    variations: [
      'kat mülkiyeti kanunu',
      'kmk 634',
      'işletme projesi',
      'genel kurul',
      'kat malikleri kurulu',
      'ortak alan giderleri',
      'aidat icra takibi',
      'gecikme tazminatı',
    ],
  },
  {
    name: '5188 Sayılı Özel Güvenlik',
    slug: 'guvenlik-yonetimi',
    pillarUrl: '/hizmetler/guvenlik-yonetimi',
    wikidata: 'https://www.wikidata.org/wiki/Q11440',
    variations: [
      'özel güvenlik',
      '5188 sayılı kanun',
      'site güvenliği',
      'kamera cctv izleme',
      'plaka tanıma sistemi',
      'devriye kontrol',
      'fiziki güvenlik',
    ],
  },
  {
    name: 'Önleyici Teknik Bakım & Asansör',
    slug: 'teknik-bakim',
    pillarUrl: '/hizmetler/teknik-bakim',
    wikidata: 'https://www.wikidata.org/wiki/Q183057',
    variations: [
      'teknik bakım',
      'asansör periyodik bakım',
      'yeşil etiket',
      'jeneratör bakımı',
      'hidrofor servisi',
      'yangın otomasyonu',
      'kompanzasyon panosu',
    ],
  },
  {
    name: 'TSE 13811 Hijyen ve Temizlik',
    slug: 'temizlik-ve-hijyen',
    pillarUrl: '/hizmetler/temizlik-ve-hijyen',
    wikidata: 'https://www.wikidata.org/wiki/Q162016',
    variations: [
      'ortak alan temizliği',
      'site temizlik firması',
      'tse 13811',
      'merdiven temizliği',
      'biyosidal dezenfeksiyon',
      'dış cephe cam temizliği',
    ],
  },
  {
    name: 'Bina Otomasyonu & Enerji Verimliliği (EKB)',
    slug: 'enerji-yonetimi',
    pillarUrl: '/hizmetler/teknik-bakim',
    wikidata: 'https://www.wikidata.org/wiki/Q895066',
    variations: [
      'bina otomasyonu',
      'enerji verimliliği',
      'enerji kimlik belgesi',
      'ekb',
      'ısı payölçer',
      'reaktif ceza önleme',
    ],
  },
  {
    name: 'Aidat Tahsilatı & Şeffaf Muhasebe',
    slug: 'aidat-takibi',
    pillarUrl: '/hizmetler/aidat-takibi',
    wikidata: 'https://www.wikidata.org/wiki/Q1670988',
    variations: [
      'aidat tahsilatı',
      'aidat takibi',
      'site muhasebesi',
      'online aidat ödeme',
      'şeffaf hesap raporu',
    ],
  },
  {
    name: 'Yangın ve Acil Durum Yönetimi',
    slug: 'acil-durum',
    pillarUrl: '/hizmetler/guvenlik-yonetimi',
    wikidata: 'https://www.wikidata.org/wiki/Q168541',
    variations: [
      'yangın tesisatı',
      'yangın merdiveni',
      'acil durum tahliye planı',
      'yangın pompası testi',
    ],
  },
  {
    name: 'Peyzaj & Otomatik Sulama Sistemleri',
    slug: 'peyzaj-ve-bahce-bakimi',
    pillarUrl: '/hizmetler/peyzaj-ve-bahce-bakimi',
    wikidata: 'https://www.wikidata.org/wiki/Q179188',
    variations: [
      'peyzaj bakımı',
      'bahçe bakımı',
      'otomatik sulama sistemi',
      'çim biçme budama',
      'ağaç ilaçlama',
    ],
  },
] as const;
